### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @azure06.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
cc @azure06

**Comment by vedantmgoyal9** [comment]
@azure06 can you please change base branch to `release/0.2.4` and merge the PR?

**Comment by azure06** [comment]
@vedantmgoyal2009 Seems there are some conflicts.

**Comment by vedantmgoyal9** [comment]
@azure06 conflicts are resolved 🎉

**Comment by vedantmgoyal9** [comment]
> Before merging this:
> 
> 1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
> 2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @azure06.

Please don't forget to do the above otherwise the action will fail to run.

**Comment by azure06** [comment]
@vedantmgoyal2009 
Do you mind giving me more details or sharing some docs? I have already created a github token and forked the repo. But I'm not sure what to do next.

**Comment by vedantmgoyal9** [comment]
- Go to https://github.com/settings/tokens/new
- Enter a token name (it can be anything, you want)
- Select `public_repo` and `workflow` in the permissions section
- Click "generate token" and copy the token to the clipboard.

After this, you've to add it as a repository secret. For this:
- Visit https://github.com/FedoraQt/MediaWriter/settings/secrets/actions/new
- Enter the information as shown in the below screenshot: 
image

Finally, it would look like this: 
image

**Pull request merged**
